(ns paragon.core-test
  (:require [clojure.test :refer :all]
            [paragon.core :refer :all]))

(deftest test-spread-black
  (turn-on-debugging)
  (let [jg (-> (new-just-graph)
               (can-explain [:h1] :s1)
               (can-explain [:h1] :s2)
               (can-explain [:h2] :s1)
               (can-explain [:h2] :s4)
               (can-explain [:h3] :s3)
               (can-explain [:h3] :s4)
               (can-explain [:j1 :j2] :h1)
               (can-explain [:j2 :j3 :j4] :h3)
               (add-inconsistencies :h2 [:h1 :h3]))
        jg-asserted (-> jg
                        (assert-color :s1 :black)
                        (assert-color :s2 :black)
                        (assert-color :s3 :black)
                        (assert-color :s4 :black))
        jg-expanded (-> jg
                        (expand :s3)
                        (expand :s1)
                        (expand :s2)
                        (expand :s4))
        jg-black (spread-black jg-asserted)
        jg-white-black (spread-white jg-black)
        jg-black-white-black (spread-black jg-white-black)
        jg-white-black-white-black (spread-white jg-black-white-black)]
    #_(visualize jg-expanded)
    (visualize jg-white-black)
    (is (= #{:s1 :s2 :s3 :s4} (set (believed jg-asserted))))
    (is (= #{:h1 :h3 :s1 :s2 :s3 :s4} (set (believed jg-white-black))))
    (is (= jg-white-black jg-black-white-black jg-white-black-white-black))))

(deftest test-peyer
  (turn-on-debugging)
  (let [jg (-> (new-just-graph)
               (can-explain [:I1] :E1)
               (can-explain [:G1] :E1)
               (can-explain [:G6] :E2)
               (can-explain [:G4] :E3)
               (can-explain [:G5] :E4)
               (can-explain [:I2] :E4)
               (can-explain [:I2] :E5)
               (can-explain [:G3] :E6)
               (can-explain [:I3] :E6)
               (can-explain [:G1] :E7)
               (can-explain [:I4] :E7)
               (can-explain [:I4a] :E8)
               (can-explain [:G2] :E9)
               (can-explain [:I5] :E9)
               (can-explain [:G1] :E10)
               (can-explain [:I6] :E10)
               (can-explain [:I6] :E11)
               (can-explain [:G7] :E12)
               (can-explain [:I7] :E12)
               (can-explain [:G8] :E13)
               (can-explain [:I7] :E13)
               (can-explain [:G1] :E14)
               (can-explain [:I1] :E14)
               (can-explain [:I1] :E16)
               (can-explain [:I8] :E17)
               (add-inconsistencies :G1 [:I1 :I8])
               (add-inconsistencies :G2 [:I5])
               (add-inconsistencies :G3 [:I3])
               (add-inconsistencies :G5 [:I2])
               (add-inconsistencies :G7 [:I7])
               (assert-black :E1)
               (assert-black :E2)
               (assert-black :E3)
               (assert-black :E4)
               (assert-black :E5)
               (assert-black :E6)
               (assert-black :E7)
               (assert-black :E8)
               (assert-black :E9)
               (assert-black :E10)
               (assert-black :E11)
               (assert-black :E12)
               (assert-black :E13)
               (assert-black :E14)
               (assert-black :E15)
               (assert-black :E16)
               (assert-black :E17))
        jg-black (spread-black jg)
        jg-white-black (spread-white jg-black)
        jg-contract-e16 (contract jg-white-black :E16)
        jg-contract-e17-e16 (contract jg-contract-e16 :E17)
        jg-contract-i4 (contract jg-white-black :I4)
        jg-contract-i1-i4 (contract jg-contract-i4 :I1)]
    (is (check-axioms jg-white-black))
    (is (check-axioms jg-contract-e16))
    (is (check-axioms jg-contract-e17-e16))
    (is (not ((set (believed jg-contract-e16)) :E16)))
    (is (not ((set (believed jg-contract-e17-e16)) :E17)))
    (is (not ((set (believed jg-contract-i4)) :I4)))
    (is (not ((set (believed jg-contract-i1-i4)) :I1)))
    #_(visualize jg)
    #_(visualize jg-black)
    #_(visualize jg-white-black)
    #_(visualize jg-contract-e16)
    #_(visualize jg-contract-e17-e16)
    #_(visualize jg-contract-i4)
    #_(visualize jg-contract-i1-i4)))

(deftest test-contraction
  (let [jg (-> (new-just-graph)
               (exists-just [:strokeA] :a)
               (exists-just [:strokeB] :b)
               (exists-just [:strokeC] :c)
               (forall-just [:a :b :c] :strokeD)
               (exists-just [:strokeD] :d)
               (assert-color :strokeA :black)
               (assert-color :strokeB :black)
               (assert-color :strokeC :black)
               (assert-color :a :black)
               (assert-color :b :black)
               (assert-color :c :black)
               (assert-color :strokeD :black)
               (assert-color :d :black))
        jg-contract-strokeA (contract jg :strokeA)
        jg-contract-strokeB (contract jg :strokeB)
        jg-contract-strokeC (contract jg :strokeC)
        jg-contract-strokeD (contract jg :strokeD)
        jg-contract-a (contract jg :a)
        jg-contract-b (contract jg :b)
        jg-contract-c (contract jg :c)
        jg-contract-d (contract jg :d)]
    (is (check-axioms-debug jg))
    (is (empty? (unbelieved jg)))
    (is (= #{:a :b :c :d} (set (believed jg))))
    (is (check-axioms-debug jg-contract-strokeA))
    (is (= :white (jgcolor jg-contract-strokeA :strokeA)))
    (is (check-axioms-debug jg-contract-strokeB))
    (is (= :white (jgcolor jg-contract-strokeB :strokeB)))
    (is (check-axioms-debug jg-contract-strokeC))
    (is (= :white (jgcolor jg-contract-strokeC :strokeC)))
    (is (check-axioms-debug jg-contract-strokeD))
    (is (= :white (jgcolor jg-contract-strokeD :strokeD)))
    (is (check-axioms-debug jg-contract-a))
    (is (= :white (jgcolor jg-contract-a :a)))
    (is (check-axioms-debug jg-contract-b))
    (is (= :white (jgcolor jg-contract-b :b)))
    (is (check-axioms-debug jg-contract-c))
    (is (= :white (jgcolor jg-contract-c :c)))
    (is (check-axioms-debug jg-contract-d))
    (is (= :white (jgcolor jg-contract-d :d)))))

(deftest test-expansion
  (let [jg (-> (new-just-graph)
               (exists-just [:strokeA] :a)
               (exists-just [:strokeB] :b)
               (exists-just [:strokeC] :c)
               (forall-just [:a :b :c] :strokeD)
               (exists-just [:strokeD] :d)
               (assert-color :strokeA :white)
               (assert-color :strokeB :white)
               (assert-color :strokeC :white)
               (assert-color :a :white)
               (assert-color :b :white)
               (assert-color :c :white)
               (assert-color :strokeD :white)
               (assert-color :d :white))
        jg-expand-strokeA (expand jg :strokeA)
        jg-expand-strokeB (expand jg :strokeB)
        jg-expand-strokeC (expand jg :strokeC)
        jg-expand-strokeD (expand jg :strokeD)
        jg-expand-a (expand jg :a)
        jg-expand-b (expand jg :b)
        jg-expand-c (expand jg :c)
        jg-expand-d (expand jg :d)]
    (is (check-axioms-debug jg))
    (is (empty? (believed jg)))
    (is (= #{:a :b :c :d} (set (unbelieved jg))))
    (is (check-axioms-debug jg-expand-strokeA))
    (is (= :black (jgcolor jg-expand-strokeA :strokeA)))
    (is (= :black (jgcolor jg-expand-strokeA :a)))
    (is (= :white (jgcolor jg-expand-strokeA :strokeD)))
    (is (= :white (jgcolor jg-expand-strokeA :d)))
    (is (= :white (jgcolor jg-expand-strokeA :strokeC)))
    (is (= :white (jgcolor jg-expand-strokeA :strokeB)))
    (is (= :white (jgcolor jg-expand-strokeA :c)))
    (is (= :white (jgcolor jg-expand-strokeA :b)))
    (is (check-axioms-debug jg-expand-strokeB))
    (is (= :black (jgcolor jg-expand-strokeB :strokeB)))
    (is (check-axioms-debug jg-expand-strokeC))
    (is (= :black (jgcolor jg-expand-strokeC :strokeC)))
    (is (check-axioms-debug jg-expand-strokeD))
    (is (and (every? (fn [n] (black? jg-expand-strokeD n)) (nodes jg-expand-strokeD))
             (every? (fn [s] (black? jg-expand-strokeD s)) (strokes jg-expand-strokeD))))
    (is (check-axioms-debug jg-expand-a))
    (is (= :black (jgcolor jg-expand-a :a)))
    (is (= :black (jgcolor jg-expand-a :strokeA)))
    (is (= :white (jgcolor jg-expand-a :strokeD)))
    (is (= :white (jgcolor jg-expand-a :d)))
    (is (check-axioms-debug jg-expand-b))
    (is (= :black (jgcolor jg-expand-b :b)))
    (is (check-axioms-debug jg-expand-c))
    (is (= :black (jgcolor jg-expand-c :c)))
    (is (check-axioms-debug jg-expand-d))
    (is (= :black (jgcolor jg-expand-d :d)))
    (is (and (every? (fn [n] (= :black (jgcolor jg-expand-d n))) (nodes jg-expand-d))
             (every? (fn [s] (= :black (jgcolor jg-expand-d s))) (strokes jg-expand-d))))))

(deftest test-inconsistencies
  (let [jg (-> (new-just-graph)
               (exists-just [:strokeA] :a)
               (exists-just [:strokeB] :b)
               (exists-just [:strokeC] :c)
               (forall-just [:a :b :c] :strokeD)
               (exists-just [:strokeD] :d)
               (assert-color :strokeA :white)
               (assert-color :strokeB :white)
               (assert-color :strokeC :white)
               (assert-color :a :white)
               (assert-color :b :white)
               (assert-color :c :white)
               (assert-color :strokeD :white)
               (assert-color :d :white)
               (add-inconsistencies :a [:b :c])
               (add-inconsistencies :b [:a :c])
               (add-inconsistencies :c [:a :b]))
        jg-expand-a (expand jg :a)
        jg-expand-b (expand jg :b)
        jg-expand-c (expand jg :c)
        jg-expand-d (expand jg :d)
        jg-expand-ab (-> jg (expand :a) (expand :b))
        jg-expand-bc (-> jg (expand :b) (expand :c))
        jg-expand-ac (-> jg (expand :a) (expand :c))
        jg-expand-abc (-> jg (expand :a) (expand :b) (expand :c))
        jg-expand-acb (-> jg (expand :a) (expand :c) (expand :b))
        jg-expand-bac (-> jg (expand :b) (expand :a) (expand :c))
        jg-expand-bca (-> jg (expand :b) (expand :c) (expand :a))
        jg-expand-cba (-> jg (expand :c) (expand :b) (expand :a))
        jg-expand-cab (-> jg (expand :c) (expand :a) (expand :b))
        jg-expand-d (-> jg (expand :d))]
    (is (= #{:a} (set (believed jg-expand-a))))
    (is (= #{:b} (set (believed jg-expand-b))))
    (is (= #{:c} (set (believed jg-expand-c))))
    (is (= #{:a :b} (set (believed jg-expand-ab))))
    (is (= #{:b :c} (set (believed jg-expand-bc))))
    (is (= #{:a :c} (set (believed jg-expand-ac))))
    (is (not= #{:a :b :c} (set (believed jg-expand-abc))))
    (is (not= #{:a :b :c} (set (believed jg-expand-acb))))
    (is (not= #{:a :b :c} (set (believed jg-expand-bac))))
    (is (not= #{:a :b :c} (set (believed jg-expand-bca))))
    (is (not= #{:a :b :c} (set (believed jg-expand-cba))))
    (is (not= #{:a :b :c} (set (believed jg-expand-cab))))
    (is (not= #{:a :b :c :d} (set (believed jg-expand-d))))))
